# themes
# include GruvBox_DarkHard.conf
# include JetBrains_Darcula.conf
include jetbrains_dark.conf

# terminal opacity and blur
# background_opacity 0.8
# background_blur 1

# set padding
window_padding_width 20

# font
font_size 13.0

# Modifier
kitty_mod ctrl+shift

# copy and paste
map cmd+c        copy_or_interrupt
map kitty_mod+v  paste_from_clipboard
map cmd+v        paste_from_clipboard

